name: main

on:
  schedule:
    - cron: "15 * * * *" # at 45 minutes past the hour, every 3 hours, between 05:00 and 23:59
    - cron: "45 5-23/3 * * *" # at 45 minutes past the hour, every 3 hours, between 05:00 and 23:59
  workflow_dispatch:

jobs:
  dtek-krem:
    name: dtek-krem
    uses: ./.github/workflows/dtek.yaml
    with:
      environment: "dtek-krem"
  dtek-oem:
    name: dtek-oem
    uses: ./.github/workflows/dtek.yaml
    with:
      environment: "dtek-oem"
